[versions]

kotlin = "1.7.21"
datastore = "1.0.0"
infrastructure = "0.17"

[libraries]

androidx-datastore = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
tink = "com.google.crypto.tink:tink-android:1.7.0"

infrastructure-kotlin = { module = "com.redmadrobot.build:infrastructure-kotlin", version.ref = "infrastructure" }
infrastructure-publish = { module = "com.redmadrobot.build:infrastructure-publish", version.ref = "infrastructure" }
